// Warning: AutoGenerated file, Don't edit.
document.writeln("<script type=\"text/javascript\" src=\"Screens/Main.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/PageTwo.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/SubSection.lsml.js\"></script>");
